FROM debian:buster-slim as stage0

RUN apt-get update
RUN apt-get install --yes curl sudo

RUN curl https://tea.xyz | PREFIX=/opt YES=1 bash

FROM debian:buster-slim as stage1
COPY --from=stage0 /opt /opt

RUN ln -s /opt/tea.xyz/v0/bin/tea /usr/local/bin/tea \
 && apt-get update \
 && apt-get --yes install libc-dev libstdc++-8-dev libgcc-8-dev sudo
