name: CI·SH

on:
  pull_request:
    paths:
      - '**.sh'

jobs:
  shell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@1.1.0
