name: CI

on:
  pull_request:

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nosborn/github-action-markdown-cli@v3.2.0
        with:
          config_file: .github/markdownlint.yml
          files: .
          dot: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@1.1.0
      - uses: actions/checkout@v3

      - name: build infuser
        run: docker build --file Dockerfile --tag infuser:ci .

      - run: docker run infuser:ci /usr/bin/tea --version

      - name: build gha-runner
        run: docker build --file gha-runner/Dockerfile gha-runner
