name: CI

on:
  pull_request:
    paths:
      - '**.sh'
      - Dockerfile
      - gha-runner/Dockerfile

jobs:
  infuser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build --file Dockerfile --tag infuser:ci .
      - name: test
        run: docker run infuser:ci /usr/bin/tea --version

  gha-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build --file gha-runner/Dockerfile gha-runner

  shell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@1.1.0
